export {
	selectCurrentNotification,
	selectHasNotification,
	selectOpenedProjectApps,
	selectQueueLength,
	selectSeenIds,
	useNotificationHasHydrated,
	useNotificationStore,
} from "./notification-store";

export { StoreHydrator, type StoreHydratorProps } from "./StoreHydrator";

export {
	selectActiveWindowId,
	selectBootPhase,
	selectBootTime,
	selectDesktopRefreshKey,
	selectDockConfig,
	selectFullscreenWindowId,
	selectIsAboutModalOpen,
	selectIsAnyWindowFullscreen,
	selectIsLocked,
	selectIsWindowActive,
	selectIsWindowFullscreen,
	selectWallpaper,
	selectWindowById,
	selectWindows,
	useHasHydrated,
	useSystemStore,
} from "./system-store";

export {
	AppID,
	AUTO_FULLSCREEN_APPS,
	type BootPhase,
	DEFAULT_DOCK_CONFIG,
	DEFAULT_WINDOW_SIZES,
	DOCK_SIZE_MAP,
	type DockConfig,
	type DockPosition,
	type DockSize,
	DockStackID,
	FULL_HEIGHT_MOBILE_APPS,
	type LaunchMethod,
	MAXIMIZED_APPS,
	MOBILE_MAXIMIZED_APPS,
	NOTIFICATION_AUTO_DISMISS,
	NOTIFICATION_QUEUE_DELAY,
	NOTIFICATION_REGISTRY,
	type NotificationActions,
	type NotificationContent,
	NotificationID,
	type NotificationInstance,
	type NotificationState,
	type NotificationStore,
	PROJECT_APP_IDS,
	type SystemActions,
	type SystemState,
	type SystemStore,
	COLOR_PALETTE,
	ICON_COLORS,
	type IconColor,
	TERMINAL_FONT_COLORS,
	type TerminalFontColor,
	type ThemeColor,
	type WindowInstance,
	type WindowPosition,
	type WindowProps,
	type WindowSize,
	type WindowSpawnConfig,
	type WindowStatus,
} from "./types";
